"""
Busca metadata de una cancion: primero parsea la descripcion auto-generada
de YouTube (Provided to YouTube by ...), si no encuentra cae a MusicBrainz.

Uso:
    from musicbrainz_lookup import lookup_song
    info = lookup_song("MONTAGEM ALQUIMIA")
    # {"artists": ["DJ XYZ", "MC ABC"], "label": "Some Records", "matched": True}

Si no encuentra nada (canciones underground / desconocidas), devuelve:
    {"artists": [], "label": None, "matched": False}
"""
from __future__ import annotations
import re
import time
import requests

USER_AGENT = "AuraInfinite10/1.0 (canal de canciones virales)"
API_BASE = "https://musicbrainz.org/ws/2"
TIMEOUT = 8


def _clean_query(title: str) -> str:
    """Limpia el titulo para buscar mejor: quita SLOWED/REVERB/SPED UP/etc."""
    t = title
    # Quitar marcadores comunes que MusicBrainz no indexa
    patterns = [
        r"\(slowed[^\)]*\)", r"\[slowed[^\]]*\]",
        r"\(sped\s*up[^\)]*\)", r"\[sped\s*up[^\]]*\]",
        r"\(reverb[^\)]*\)", r"\(8d[^\)]*\)",
        r"\(remix[^\)]*\)",
        r"\bslowed\b", r"\bsped up\b", r"\breverb\b",
        r"\bofficial\b", r"\bvideo\b", r"\bvisualizer\b",
        r"\bhq\b", r"\bhd\b",
    ]
    for p in patterns:
        t = re.sub(p, "", t, flags=re.IGNORECASE)
    t = re.sub(r"\s+", " ", t).strip(" -|")
    return t


def parse_youtube_auto_description(description: str) -> dict:
    """Parsea la descripcion auto-generada de YouTube ('Provided to YouTube by...')
    para extraer artistas y label.

    Formato tipico:
        Provided to YouTube by <distribuidora>
        <Titulo> · <Artista1> · <Artista2> · ...
        <Album>
        ℗ <year> <Label>
        ...

    Devuelve: {"artists": [...], "label": str|None, "matched": bool}
    """
    if not description:
        return {"artists": [], "label": None, "matched": False}

    # 1) Detectar el patron auto-generado
    if "Provided to YouTube by" not in description and "Auto-generated by YouTube" not in description:
        # Aceptamos uno u otro: a veces aparece solo "Auto-generated"
        if "·" not in description:
            return {"artists": [], "label": None, "matched": False}

    artists: list[str] = []
    label: str | None = None

    # 2) Extraer artistas: linea con ' · ' que viene tras "Provided to YouTube by ..."
    for line in description.splitlines():
        if "·" in line:
            parts = [p.strip() for p in line.split("·")]
            # parts[0] = titulo, resto = artistas
            if len(parts) >= 2:
                artists = parts[1:]
                # Limpiar duplicados manteniendo orden
                artists = list(dict.fromkeys(artists))
                break

    # 3) Extraer label: linea que empieza con ℗ (P circulada = phonogram)
    p_match = re.search(r"℗\s*(?:\d{4}\s+)?(.+?)(?:\n|$)", description)
    if p_match:
        label_raw = p_match.group(1).strip()
        # Si dice "X under exclusive license to Y", el label real es Y
        m = re.search(r"under exclusive license to\s+(.+?)(?:\.|$)", label_raw)
        if m:
            label = m.group(1).strip().rstrip(".")
        else:
            # Si dice "Provided to YouTube by X", X suele ser distribuidor, no label.
            # En ese caso, primer linea con "Provided to YouTube by" se descarta y
            # se usa el del ℗.
            label = label_raw.rstrip(".")

    matched = bool(artists or label)
    return {"artists": artists, "label": label, "matched": matched}


def lookup_song(title: str) -> dict:
    """Busca una grabacion en MusicBrainz. Devuelve dict con artists + label."""
    query = _clean_query(title)
    if not query:
        return {"artists": [], "label": None, "matched": False, "title_clean": ""}

    # 1) Buscar la grabacion mas relevante
    try:
        res = requests.get(
            f"{API_BASE}/recording",
            params={"query": query, "fmt": "json", "limit": 5},
            headers={"User-Agent": USER_AGENT},
            timeout=TIMEOUT,
        )
        res.raise_for_status()
    except requests.RequestException:
        return {"artists": [], "label": None, "matched": False, "title_clean": query}

    data = res.json()
    recordings = data.get("recordings", [])
    if not recordings:
        return {"artists": [], "label": None, "matched": False, "title_clean": query}

    # Tomar la primera con score alto (>=80)
    best = recordings[0]
    if best.get("score", 0) < 80:
        return {"artists": [], "label": None, "matched": False, "title_clean": query}

    artists = []
    for ac in best.get("artist-credit", []):
        if isinstance(ac, dict) and ac.get("artist", {}).get("name"):
            artists.append(ac["artist"]["name"])
    artists = list(dict.fromkeys(artists))  # dedup

    # 2) Buscar el label desde el primer release del recording
    label = None
    releases = best.get("releases", [])
    if releases:
        release_id = releases[0].get("id")
        if release_id:
            time.sleep(1.0)  # MusicBrainz pide 1 req/seg
            try:
                r2 = requests.get(
                    f"{API_BASE}/release/{release_id}",
                    params={"fmt": "json", "inc": "labels"},
                    headers={"User-Agent": USER_AGENT},
                    timeout=TIMEOUT,
                )
                if r2.ok:
                    rj = r2.json()
                    label_info = rj.get("label-info", [])
                    if label_info and label_info[0].get("label"):
                        label = label_info[0]["label"].get("name")
            except requests.RequestException:
                pass

    return {
        "artists": artists,
        "label": label,
        "matched": True,
        "title_clean": query,
        "score": best.get("score"),
    }


if __name__ == "__main__":
    import sys
    title = sys.argv[1] if len(sys.argv) > 1 else "MONTAGEM ALQUIMIA"
    info = lookup_song(title)
    print(f"Query: {info['title_clean']}")
    print(f"Matched: {info['matched']}")
    print(f"Artists: {info['artists']}")
    print(f"Label: {info['label']}")
